name: Daily Jupiter Staking & Wallets Update
on:
  schedule:
    # Run daily at 01:00 UTC (adjust timezone as needed)
    - cron: '0 1 * * *'
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  update-staking-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        npm init -y
        npm install dotenv
        
    - name: Run Jupiter staking update
      env:
        HELIUS_API_KEY: ${{ secrets.HELIUS_API_KEY }}
      run: node daily_updater.js
      
    - name: Check for changes
      id: verify-changed-files
      run: |
        # Check if either file has changes
        COMBINED_CHANGED=false
        WALLETS_CHANGED=false
        
        if ! git diff --quiet jupiter_combined_staking.json; then
          COMBINED_CHANGED=true
          echo "Changes detected in jupiter_combined_staking.json"
        fi
        
        if ! git diff --quiet wallet_states.json; then
          WALLETS_CHANGED=true
          echo "Changes detected in wallet_states.json"
        fi
        
        if [ "$COMBINED_CHANGED" = true ] || [ "$WALLETS_CHANGED" = true ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "combined_changed=$COMBINED_CHANGED" >> $GITHUB_OUTPUT
          echo "wallets_changed=$WALLETS_CHANGED" >> $GITHUB_OUTPUT
        else
          echo "No changes detected in any files"
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add changed files
        if [ "${{ steps.verify-changed-files.outputs.combined_changed }}" = "true" ]; then
          git add jupiter_combined_staking.json
          echo "Added jupiter_combined_staking.json"
        fi
        
        if [ "${{ steps.verify-changed-files.outputs.wallets_changed }}" = "true" ]; then
          git add wallet_states.json
          echo "Added wallet_states.json"
        fi
        
        # Create descriptive commit message
        COMMIT_MSG="Daily Jupiter data update for $(date -u +%Y-%m-%d)"
        
        if [ "${{ steps.verify-changed-files.outputs.combined_changed }}" = "true" ] && [ "${{ steps.verify-changed-files.outputs.wallets_changed }}" = "true" ]; then
          COMMIT_MSG="$COMMIT_MSG - Updated staking totals and wallet states"
        elif [ "${{ steps.verify-changed-files.outputs.combined_changed }}" = "true" ]; then
          COMMIT_MSG="$COMMIT_MSG - Updated staking totals"
        elif [ "${{ steps.verify-changed-files.outputs.wallets_changed }}" = "true" ]; then
          COMMIT_MSG="$COMMIT_MSG - Updated wallet states"
        fi
        
        git commit -m "$COMMIT_MSG"
        git push
        
    - name: No changes to commit
      if: steps.verify-changed-files.outputs.changed == 'false'
      run: echo "No new Jupiter staking data to commit"