name: Daily Jupiter Staking Update

on:
  schedule:
    # Run daily at 01:00 UTC (adjust timezone as needed)
    - cron: '0 1 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  update-staking-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run daily staking update
      env:
        HELIUS_API_KEY: ${{ secrets.HELIUS_API_KEY }}
      run: node daily_updater_workflow.js
      
    - name: Check for changes
      id: verify-changed-files
      run: |
        if git diff --quiet; then
          echo "No changes detected"
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "Changes detected"
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add jupiter_staking_data.json
        git commit -m "Daily staking data update for $(date -u +%Y-%m-%d)"
        git push
        
    - name: No changes to commit
      if: steps.verify-changed-files.outputs.changed == 'false'
      run: echo "No new staking data to commit"